baseURL = "https://cenum.org/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Central European Network of Urban Morphology"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = false
  # highlightColor = '#003E5B'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  # headingColor = "#1c1b1d"
  # textColor = "#4e5157"
  # dotColor = "#C51D48"
  # enableGoogleFonts = true
  # googleFontsUrl = "https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap"
  # fontFamilyHeading = "Merriweather"
  # fontFamilyParagraph = "Merriweather"
  # fontFamilyMonospace = "monospace"
  # logo = "uscuni_logo.svg"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  # [[menu.main]]
  #   name = "Network"
  #   identifier = "news"
  #   weight = 2
  #   url = "/network/"
  [[menu.main]]
    name = "ISUF"
    identifier = "isuf"
    weight = 3
    url = "https://urbanform.org"